- name: install nginx
  hosts: frontend
  tasks:
   - name: install nginx in node 01
     package: 
      name: nginx
      state: present

   - name: start servie
      service: nginx
      state: started