- name: remove nginx and disable
  hosts: frontend
  become: yes
  tasks:
    - name: remove nginx
      package: 
        name: nginx
        state: absent

    - name: service down
      service:
        name: nginx
        state: stoped
        
        