- name: demo variable
  hosts: localhost
  connection: local
  vars:
   COURSE: "Ansible"
   TRAINER: "siva"
   DURATION: "150HRS"
  tasks:
  - debug:
      msg: "hi, i am learning {{COURSE}}, trainer is {{TRAINER}}, duration is {{DURATION}}"
