- name: demo variable
  hosts: localhost
  connection: local
  vars_files:
  - course.yaml

  tasks:
  - name:
    debug:
      msg: "hi, i am learning {{COURSE}}, trainer is {{TRAINER}}, duration is {{DURATION}}"
