- name:
  hosts: frontend
  tasks:
  - name: print if redhat
    debug:
      msg: "OS family is Redhat, package manager is dnf"
    when: ansible.facts.os_family == "Redhat"

  - name: print if Debian
    debug:
      msg: "OS family is Redhat, package manager is apt-get"
    when: ansible.facts.os_family == "Debian"    