# - name: demo loops
#   hosts: local
#   connection: local
#   tasks:
#   - name: greet everyone
#     debug:
#       msg: "Hi {{ item }}" # item is reserved special variable
#     loop:
#     - Ramesh
#     - Raheem
#     - John



- name: demo on loops
  hosts: local
  connection: local
  tasks:
    - name: print name
      debug:
        msg: "hi {{ item }}"

      loop:
      - harish
      - Ramesh
      - ram 


- name: install packages
  hosts: frontend
  become: yes        # run as sudo
  tasks:
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - mongodb-mongosh
    - git