# - name: demo loops
#   hosts: local
#   connection: local
#   tasks:
#   - name: greet everyone
#     debug:
#       msg: "Hi {{ item }}" # item is reserved special variable
#     loop:
#     - Ramesh
#     - Raheem
#     - John



- name: demo loops
  hosts: frontend
  become: yes
  tasks:
    - name: print name
      debug:
        msg: "hi {{ item }}"

      loop:
      - harish
      - Ramesh
      - ram 