# - name: install packages
#   hosts: frontend
#   become: yes
#   tasks:
#     - name: install packages
#       package:
#         name: "{{ item }}"
#         state: present
#       loop:
#        - nginx
#        - mysql
#        - git 


- name: install packages
  hosts: frontend
  become: yes
  tasks:
    - name: install packages
      package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
       - { name: nginx, state: absent }
       - { name: sql, state: absent }
       - { name: zip, state: present } 